Feat/makedeb and tests rewrite (#7)
* fix: Adjust sudoers file permissions.

* fix: Don't redirect _everything_ ...

* misc: Adjust whitespace.

* feat: Use ${VERSION} in pkgver.

* ci: Add scenarios tests.

* fix: Add missing Makefile target.

* fix: Try to use docker login action.

* fix: try with different token.

* ci: Use dynamic feature matrix.

* fix:typo

* refactor: Rewrite install.sh

No longer use nanolayer.
Don't bother with makedeb ppa, use .deb from github.

* fix: Use apt, which can fetch dependencies.

* fix: shadow pkgver(), makedeb is kinda buggy there.

* misc: sync

* fix: don't shadow VERSION via _buildenv eval.

* misc: Upgrade actions.

* fix: Add default value for bindist (empty).

* feat: Try to validate only one feature json at a time.

* refactor: Port nvm.

* fix: Add pkgver(). Hardcode 1.

diff --git a/src/ghc/PKGBUILD b/src/ghc/PKGBUILD
--- a/src/ghc/PKGBUILD
+++ b/src/ghc/PKGBUILD
@@ -4,7 +4,16 @@ pkgver="${VERSION}"
 pkgrel=1
 arch=(amd64)
 url="https://github.com/haskell/${pkgname}-hs"
-_buildenv=(BINDIST VERSION)
+_buildenv=(BINDIST)
+
+pkgver() {
+  command -v ghcup &>/dev/null || { echo "ghcup not found"; exit 1; }
+  case "${VERSION:-"latest"}" in
+    "latest") : "$(ghcup list -t ghc -r 2>/dev/null | cut -d' ' -f 2 | tail -1)" ;;
+    *) : "${VERSION}" ;;
+  esac
+  echo "$_"
+}
 
 package() {
   local option_bindist=()
